# Generated by Django 2.1.7 on 2019-03-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_mylist'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sub_email',
            field=models.TextField(null=True),
        ),
    ]
